return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    opts = {
      flavour = "mocha",
      transparent_background = true,
      term_colors = true,
      color_overrides = {
        mocha = {
          base = "#0F0E1A",
          mantle = "#0A0916",
          crust = "#050409",
          text = "#CDD6E8",
          subtext1 = "#A8B0C8",
          subtext0 = "#8A92AA",
          overlay2 = "#6B7089",
          overlay1 = "#4C566A",
          overlay0 = "#2A2938",
          surface2 = "#3A3948",
          surface1 = "#2A2938",
          surface0 = "#1A1928",
          blue = "#A8C0E8",
          lavender = "#C8A8E8",
          sapphire = "#A8D8E0",
          sky = "#A8D8E0",
          teal = "#A8D8B8",
          green = "#A8D8B8",
          yellow = "#E8D8A0",
          peach = "#E8C0A0",
          maroon = "#E8A0A0",
          red = "#E8A0A0",
          mauve = "#C8A8E8",
          pink = "#E8A0D0",
          flamingo = "#E8B8B8",
          rosewater = "#E8C8C0",
        },
      },
      integrations = {
        cmp = true,
        gitsigns = true,
        nvimtree = true,
        treesitter = true,
        notify = true,
        mini = true,
        which_key = true,
        native_lsp = {
          enabled = true,
        },
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin",
    },
  },
}
